apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup-job-sa
  namespace: project
  annotations:
    iam.gke.io/gcp-service-account: postgres-backup-sa@PROJECT_ID_PLACEHOLDER.iam.gserviceaccount.com
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-job-db-secret
  namespace: project
type: Opaque
stringData:
  # I know I know, I'm just a bit lazy here...
  # In real envs I'd use solutions like Azure Key Vault or so for these
  POSTGRES_USER: "todoapp"
  POSTGRES_PASSWORD: "todoapp"
  POSTGRES_DB: "todoapp"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-postgres
  namespace: project
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: postgres-backup-job-sa
          containers:
          - name: backup-postgres
            image: google/cloud-sdk:alpine
            command: ["/bin/sh", "-c"]
            args:
              - |
                apk add --no-cache postgresql-client &&
                TIMESTAMP=$(date +%Y-%m-%d-%H-%M)
                BACKUP_FILE="backup-$TIMESTAMP.sql"
                BUCKET_URL="gs://dwk-postgres-backups-${GCP_PROJECT_ID}"
                DB_HOST="todoapp-postgres"
                pg_dump -h $DB_HOST -U $DB_USER $DB_NAME > $BACKUP_FILE &&
                gsutil cp $BACKUP_FILE $BUCKET_URL/$BACKUP_FILE
            env:
              - name: GCP_PROJECT_ID
                value: "PROJECT_ID_PLACEHOLDER" 
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: backup-job-db-secret
                    key: POSTGRES_PASSWORD
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: backup-job-db-secret
                    key: POSTGRES_USER
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: backup-job-db-secret
                    key: POSTGRES_DB
          restartPolicy: OnFailure
