apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ./../../base
- cronjob-postgres-backup.yaml

namespace: prod-todo-app

images:
- name: BACKEND_IMAGE
  newName: ghcr.io/pekk4/devopswithkubernetes-todo_backend
  newTag: 5fd74e44d82e3d7d4a490f13b1e915109b3b93ce
- name: FRONTEND_IMAGE
  newName: ghcr.io/pekk4/devopswithkubernetes-todo_frontend
  newTag: 5fd74e44d82e3d7d4a490f13b1e915109b3b93ce
- name: postgres
  newTag: "15"
