apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ./../../base
- cronjob-postgres-backup.yaml

namespace: prod-todo-app

images:
- name: BACKEND_IMAGE
  newTag: 4.5.2
- name: FRONTEND_IMAGE
  newTag: 4.5.2
- name: postgres
  newTag: "15"
