apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gateway.yaml
- pvc.yaml
- postgres-statefulset.yaml
- backend-deployment.yaml
- backend-service.yaml
- backend-http-route.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- frontend-http-route.yaml
- cronjob-create-todo-hourly.yaml
