apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-app
  namespace: exercises
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: log-app
  template:
    metadata:
      labels:
        app: log-app
    spec:
      containers:
        - name: log-app-writer
          image: ghcr.io/pekk4/devopswithkubernetes-log_output
          imagePullPolicy: Always
          env:
            - name: ROLE
              value: "writer"
          volumeMounts:
            - name: log-output
              mountPath: /logs
          resources:
            requests:
              memory: "32Mi"
              cpu: "20m"
            limits:
              memory: "64Mi"
              cpu: "50m"
        - name: log-app-server
          image: ghcr.io/pekk4/devopswithkubernetes-log_output
          imagePullPolicy: Always
          volumeMounts:
            - name: log-output
              mountPath: /logs
            - name: information
              mountPath: /information
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-app-configmap
                  key: MESSAGE
          resources:
            requests:
              memory: "32Mi"
              cpu: "20m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: log-output
          persistentVolumeClaim:
            claimName: pingpong-log-pvc
        - name: information
          configMap:
            name: log-app-configmap
