apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: log-app-route
  namespace: exercises
spec:
  parentRefs:
  - name: log-app-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /status
    backendRefs:
    - name: log-app-svc
      port: 666
