apiVersion: v1
kind: Service
metadata:
  name: log-app-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: log-app
  ports:
    - port: 666
      protocol: TCP
      targetPort: 3000