apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: exercises-cpu-rate
  namespace: exercises
spec:
  metrics:
    - name: cpu-rate
      initialDelay: 1m
      interval: 1m
      count: 5
      successCondition: result[0] < 0.02
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1767-prometheus.prometheus.svc.cluster.local:9090
          query: |
            sum(rate(container_cpu_usage_seconds_total{namespace="exercises"}[1m]))
