apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app
  namespace: exercises
  labels:
    app: pingpong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      containers:
      - name: ping-pong-app
        image: ghcr.io/pekk4/devopswithkubernetes-ping_pong_app:3.4
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "8080"
          - name: PG_URL
            value: "postgres://pingpong:pingpong@pingpong-postgres:5432/pingpong?sslmode=disable"
