apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ./../../base

namespace: staging-todo-app

images:
- name: BACKEND_IMAGE
  newName: ghcr.io/pekk4/devopswithkubernetes-todo_backend
  newTag: 9b2ba634df42d03514a2388b238896d83c97d5fd
- name: FRONTEND_IMAGE
  newName: ghcr.io/pekk4/devopswithkubernetes-todo_frontend
  newTag: 9b2ba634df42d03514a2388b238896d83c97d5fd
- name: postgres
  newTag: "15"
