apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ./../../base

namespace: staging-todo-app

images:
- name: BACKEND_IMAGE
  newName: ghcr.io/pekk4/devopswithkubernetes-todo_backend
  newTag: 73e4a84c6eae5dcd1830b1ca9893005df18f4cd1
- name: FRONTEND_IMAGE
  newName: ghcr.io/pekk4/devopswithkubernetes-todo_frontend
  newTag: 73e4a84c6eae5dcd1830b1ca9893005df18f4cd1
- name: postgres
  newTag: "15"
