apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ./../../base

namespace: staging-todo-app

images:
- name: BACKEND_IMAGE
  newName: ghcr.io/pekk4/devopswithkubernetes-todo_backend
  newTag: 08342ebfe1e4957c1a15364669fd71d07dc92b9e
- name: FRONTEND_IMAGE
  newName: ghcr.io/pekk4/devopswithkubernetes-todo_frontend
  newTag: 08342ebfe1e4957c1a15364669fd71d07dc92b9e
- name: postgres
  newTag: "15"
