name: Build & Publish Todo App

on:
  push:
    branches:
      - main
    paths:
      - 'project/**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize repo name to lowercase
        run: echo "REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build & push backend image
        run: |
          IMAGE=ghcr.io/${{ env.REPO }}-todo_backend:${{ github.sha }}
          docker build -t $IMAGE -t ghcr.io/${{ env.REPO }}-todo_backend:latest --push ./project/todo-backend
          echo "BACKEND_IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Build & push frontend image
        run: |
          IMAGE=ghcr.io/${{ env.REPO }}-todo_frontend:${{ github.sha }}
          docker build -t $IMAGE -t ghcr.io/${{ env.REPO }}-todo_frontend:latest --push ./project/todo-frontend
          echo "FRONTEND_IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          repository: pekk4/dvk-todoapp-config
          path: config-repo
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Set Git identity
        run: |
          cd config-repo
          git config user.name "Voldemort"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update staging manifests
        if: github.ref == 'refs/heads/main'
        run: |
          cd config-repo/overlays/staging
          kustomize edit set image BACKEND_IMAGE=${{ env.BACKEND_IMAGE }}
          kustomize edit set image FRONTEND_IMAGE=${{ env.FRONTEND_IMAGE }}

      - name: Commit and push to staging
        if: github.ref == 'refs/heads/main'
        run: |
          cd config-repo
          git add overlays/staging/kustomization.yaml
          git commit -m "Deploy staging ${{ github.sha }}" || echo "No changes to commit"
          git push

      - name: Update prod manifests
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd config-repo/overlays/prod
          kustomize edit set image BACKEND_IMAGE=${{ env.BACKEND_IMAGE }}
          kustomize edit set image FRONTEND_IMAGE=${{ env.FRONTEND_IMAGE }}

      - name: Commit and push to prod
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd config-repo
          git add overlays/prod/kustomization.yaml
          git commit -m "Deploy prod ${{ github.ref_name }}" || echo "No changes to commit"
          git push
