name: Build & Publish Log Output App

on:
  push:
    branches:
      - main
    paths:
      - 'log_output/VERSION'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version
        id: version
        run: echo "VERSION=$(cat log_output/VERSION)" >> $GITHUB_ENV

      - name: Normalize repo name to lowercase
        run: echo "REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build & push Log output image
        run: |
          IMAGE=ghcr.io/${{ env.REPO }}-log_output:${{ env.VERSION }}
          docker build -t $IMAGE -t ghcr.io/${{ env.REPO }}-log_output:latest --push ./log_output

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Set correct image
        run: |
          cd log_output
          kustomize edit set image ghcr.io/pekk4/devopswithkubernetes-log_output=ghcr.io/pekk4/devopswithkubernetes-log_output:${{ env.VERSION }}

      - name: Update kustomization.yaml
        uses: EndBug/add-and-commit@v9
        with:
          add: 'log_output/kustomization.yaml'
          message: 'New version released ${{ env.VERSION }}'
